version: '3.9'
name: auth-api-dev

services:
  db:
    container_name: auth-api-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: auth_dev
    ports:
      - '5432:5432'
