name: Linting

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  lint:
    strategy:
      fail-fast: true

    name: Lint Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
      - name: Change Dir
        run: cd backend
      - run: npm ci
      - name: Run lint-staged
        run: npx lint-staged --diff="origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF}"
        id: lint
