name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  lint:
    strategy:
      fail-fast: true

    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
      - name: Change Dir
        run: cd backend
      - run: npm ci
      - name: Run unit tests
        run: npm test
        id: test
